name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup
        run: gradle wrapper --gradle-version 8.2
      - name: Fix
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew assembleDebug
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ArenaGoldAPK
          path: app/build/outputs/apk/debug/*.apk





          
